import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Image src={'/openchain-logo.svg'} width="48" height="48"/>
        <div className={styles.logoText}>
          OpenChain
        </div>
        <div className={styles.rightLinks}>
          <a
            href="https://twitter.com/chain_xvi"
            target="_blank"
            rel="noopener noreferrer"
          >
            Twitter
          </a>
        </div>
      </header>
      <main className={styles.main}>
        <section className={styles.heroSection}>
          <div className={styles.leftPart}>
            <h1 className={styles.heading}>
              Decentralized web3 platform for developers
            </h1>
            <p className={styles.mainParagraph}>
              OpenChain is a decentralized hub for developers on the web3 internet to bring people and their assets together. Ask questions, get paid crypto bounties to answer them, discuss concepts and notions, write blogs, or sell CSS art.
            </p>
          </div>
          <div className={styles.rightPart}>

          </div>
        </section>
      </main>
    </div>
  )
}

export default Home
